/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.OrderBy;
import io.swagger.model.SimpleUser;
import io.swagger.model.UserWithDescription;
import io.swagger.model.UserWithId;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-06-22T11:03:20.924Z[GMT]")
@Validated
public interface UsersApi {

    @Operation(summary = "Gets list of users", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Gets an array of users", content = @Content(array = @ArraySchema(schema = @Schema(implementation = UserWithId.class)))) })
    @RequestMapping(value = "/users",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<UserWithId>> usersGet(@Parameter(in = ParameterIn.QUERY, description = "allows to choose the ranking order" ,schema=@Schema()) @Valid @RequestParam(value = "orderBy", required = false) OrderBy orderBy, @Min(0)@Parameter(in = ParameterIn.QUERY, description = "number of desired page" ,schema=@Schema(allowableValues={  }
, defaultValue="0")) @Valid @RequestParam(value = "pageIndex", required = false, defaultValue="0") Integer pageIndex, @Min(1) @Max(100) @Parameter(in = ParameterIn.QUERY, description = "" ,schema=@Schema(allowableValues={  }, minimum="1", maximum="100"
, defaultValue="20")) @Valid @RequestParam(value = "numElements", required = false, defaultValue="20") Integer numElements);


    @Operation(summary = "Creates new user", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Returns a copy of created user object", content = @Content(schema = @Schema(implementation = UserWithDescription.class))) })
    @RequestMapping(value = "/users",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<UserWithDescription> usersPost(@Parameter(in = ParameterIn.DEFAULT, description = "A JSON object containing new user data", required=true, schema=@Schema()) @Valid @RequestBody SimpleUser body);

}

