server:
  port: 8080
spring:
  jackson:
     property-naming-strategy: SNAKE_CASE
     default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://dm_postgres:5432/DataManager
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        types:
          print:
            banner: false
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml

logging:
  level:
    root: info